services:
  mlflow_db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    volumes:
      - ../db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'